# Generated by Django 3.2.9 on 2021-11-26 05:51

import accounts.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='メールアドレス')),
                ('last_name', models.CharField(max_length=150, verbose_name='姓')),
                ('first_name', models.CharField(default='1', max_length=150, verbose_name='名')),
                ('last_name_kana', models.CharField(default='1', max_length=150, verbose_name='姓（かな）')),
                ('first_name_kana', models.CharField(default='1', max_length=150, verbose_name='名（かな）')),
                ('sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='1', max_length=4, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（ハイフンなし）')),
                ('prefecture', models.CharField(blank=True, max_length=5, null=True, verbose_name='都道府県')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='市区町村番地')),
                ('building', models.CharField(blank=True, max_length=30, null=True, verbose_name='建物名')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='電話番号（ハイフンなし）')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'User',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='T002Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.BooleanField(blank=True, null=True, verbose_name='通知')),
            ],
        ),
        migrations.CreateModel(
            name='T003Childminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=150, verbose_name='ユーザ種別')),
            ],
        ),
    ]
