# Generated by Django 3.2.9 on 2022-02-04 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t003childminder',
            name='class_id',
            field=models.ForeignKey(default='1', max_length=3, on_delete=django.db.models.deletion.CASCADE, to='main.t004class', verbose_name='クラスID'),
        ),
        migrations.AddField(
            model_name='t003childminder',
            name='user',
            field=models.OneToOneField(help_text='登録したユーザ名を選択', on_delete=django.db.models.deletion.CASCADE, related_name='detail_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='t002parents',
            name='user',
            field=models.OneToOneField(help_text='登録したユーザ名を選択', on_delete=django.db.models.deletion.CASCADE, related_name='detail_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.usertype', verbose_name='ユーザ種別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
