# Generated by Django 3.2.9 on 2021-11-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t002parents',
            options={'verbose_name_plural': '保護者テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t003childminder',
            options={'verbose_name_plural': '保育士テーブル'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='building',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prefecture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='住所'),
        ),
    ]
