# Generated by Django 3.2.9 on 2021-11-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211129_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], default='男性', max_length=4, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='t002parents',
            name='notification',
            field=models.BooleanField(default=True, verbose_name='通知'),
        ),
    ]
