# Generated by Django 3.2.9 on 2021-11-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211119_0930'),
        ('accounts', '0004_alter_customuser_table'),
    ]

    operations = [
    ]
