# Generated by Django 3.2.9 on 2021-11-30 03:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T001Children',
            fields=[
                ('t001_pk01_children_id', models.CharField(db_column='T001_PK01_children-id', max_length=150, primary_key=True, serialize=False, verbose_name='園児ID')),
                ('t001_fd01_last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('t001_fd07_first_name', models.CharField(max_length=20, verbose_name='名')),
                ('t001_fd08_last_name_kana', models.CharField(max_length=20, verbose_name='姓（かな）')),
                ('t001_fd09_first_name_kana', models.CharField(max_length=20, verbose_name='名（かな）')),
                ('t001_fd06_sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], db_column='T001_FD06_sex', default='男性', max_length=4, verbose_name='性別')),
                ('t001_fd02_birthday', models.DateField(db_column='T001_FD02_birthday', verbose_name='誕生日')),
                ('t001_fd10_postal_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（ハイフンなし）')),
                ('t001_fd03_address', models.CharField(db_column='T001_FD03_address', max_length=50, verbose_name='住所')),
                ('t001_fd04_createdata', models.DateTimeField(db_column='T001_FD04_createdata', verbose_name='作成日時')),
                ('t001_fd05_updatedata', models.DateTimeField(blank=True, db_column='T001_FD05_updatedata', null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': '園児テーブル',
                'db_table': 'T001_children',
            },
        ),
        migrations.CreateModel(
            name='T004Class',
            fields=[
                ('t004_pk01_class_id', models.CharField(db_column='T004_PK01_class-id', max_length=3, primary_key=True, serialize=False, verbose_name='クラスID')),
                ('t004_fd01_class_name', models.CharField(db_column='T004_FD01_class-name', max_length=20, verbose_name='クラス名')),
                ('t004_fd02_year', models.IntegerField(db_column='T004_FD02_year', verbose_name='学年')),
            ],
            options={
                'verbose_name_plural': 'クラステーブル',
                'db_table': 'T004_class',
            },
        ),
        migrations.CreateModel(
            name='T010Playset',
            fields=[
                ('t010_pk01_playset_id', models.CharField(db_column='T010_PK01_playset-id', max_length=10, primary_key=True, serialize=False, verbose_name='遊具ID')),
                ('t010_fd01_playset_name', models.CharField(db_column='T010_FD01_playset-name', max_length=30, verbose_name='遊具名')),
                ('t010_fd02_distance_a', models.FloatField(db_column='T010_FD02_distance-a', verbose_name='アンカーaからの遊具までの距離')),
                ('t010_fd03_distance_b', models.FloatField(db_column='T010_FD03_distance-b', verbose_name='アンカーbからの遊具までの距離')),
                ('t010_fd04_distance_c', models.FloatField(db_column='T010_FD04_distance-c', verbose_name='アンカーcからの遊具までの距離')),
            ],
            options={
                'verbose_name_plural': '遊具テーブル',
                'db_table': 'T010_playset',
            },
        ),
        migrations.CreateModel(
            name='T005Kindergaten',
            fields=[
                ('t005_pk01_childen_id', models.OneToOneField(db_column='T005_PK01_childen-id', max_length=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.t001children', verbose_name='園児ID')),
                ('t005_fd01_date', models.DateField(db_column='T005_FD01_date', default=datetime.date.today, verbose_name='日付')),
                ('t005_fd02_school_time', models.TimeField(blank=True, db_column='T005_FD02_school-time', null=True, verbose_name='登園時間')),
                ('t005_fd03_exit_time', models.TimeField(blank=True, db_column='T005_FD03_exit-time', null=True, verbose_name='降園時間')),
                ('t005_fd04_status', models.CharField(choices=[('登園', '登園'), ('降園', '降園')], db_column='T005_FD04_status', default='登園', max_length=4, verbose_name='登園状態')),
            ],
            options={
                'verbose_name_plural': '登園状態テーブル',
                'db_table': 'T005_kindergaten',
            },
        ),
        migrations.CreateModel(
            name='T012Contactbooktem',
            fields=[
                ('t012_pk01_contactbook_id', models.CharField(db_column='T012_PK01_contactbook-id', max_length=10, primary_key=True, serialize=False, verbose_name='連絡帳テンプレートID')),
                ('t012_fd01_date', models.DateField(blank=True, db_column='T012_FD01_date', null=True, verbose_name='日時')),
                ('t012_fd02_information', models.CharField(blank=True, db_column='T012_FD02_information', max_length=200, null=True, verbose_name='備考')),
                ('t012_fd03_mealtime', models.TimeField(blank=True, db_column='T012_FD03_mealtime', null=True, verbose_name='食事時間')),
                ('t012_fd04_meal_contents', models.CharField(blank=True, db_column='T012_FD04_meal-contents', max_length=100, null=True, verbose_name='食事内容')),
                ('t012_fd05_bed_time', models.TimeField(blank=True, db_column='T012_FD05_bed-time', null=True, verbose_name='就寝時間')),
                ('t012_fd06_wakeup_time', models.TimeField(blank=True, db_column='T012_FD06_wakeup-time', null=True, verbose_name='起床時間')),
                ('t012_fd07_updatedata', models.DateTimeField(db_column='T012_FD07_updatedata', verbose_name='更新日時')),
                ('t012_fk01_childminder_id', models.ForeignKey(db_column='T012_FK01_childminder-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.t003childminder', verbose_name='保育士ID')),
            ],
            options={
                'verbose_name_plural': '連絡帳テンプレートテーブル',
                'db_table': 'T012_contactbooktem',
            },
        ),
        migrations.CreateModel(
            name='T011Room',
            fields=[
                ('t011_pk01_room_id', models.CharField(db_column='T011_PK01_room-id', max_length=100, primary_key=True, serialize=False, verbose_name='ルームID')),
                ('t011_fk01_parents_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.t002parents', verbose_name='保護者ID')),
                ('t011_fk02_chilminder_id', models.ForeignKey(db_column='T011_FK02_chilminder-id', default='1', max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.t003childminder', verbose_name='保育士ID')),
            ],
            options={
                'verbose_name_plural': 'ルームテーブル',
                'db_table': 'T011_room',
            },
        ),
        migrations.CreateModel(
            name='T008Schedule',
            fields=[
                ('t008_pk01_schedule_id', models.CharField(db_column='T008_PK01_schedule-id', max_length=10, primary_key=True, serialize=False, verbose_name='スケジュールID')),
                ('t008_fd01_event', models.CharField(db_column='T008_FD01_event', max_length=100, verbose_name='イベント名')),
                ('t008_fd02_remarks', models.CharField(blank=True, db_column='T008_FD02_remarks', max_length=200, null=True, verbose_name='情報')),
                ('t008_fd03_date', models.DateField(db_column='T008_FD03_date', verbose_name='開催日')),
                ('t008_fd06_time', models.TimeField(blank=True, db_column='T008_FD06_time', null=True, verbose_name='開催時間')),
                ('t008_fd04_updatedata', models.DateTimeField(db_column='T008_FD04_updatedata', verbose_name='作成日時')),
                ('t008_fd05_createdata', models.DateTimeField(blank=True, db_column='T008_FD05_createdata', null=True, verbose_name='更新日時')),
                ('t008_fk01_class_id', models.ForeignKey(db_column='T008_FK01_class-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='main.t004class', verbose_name='クラスID')),
            ],
            options={
                'verbose_name_plural': 'スケジュールテーブル',
                'db_table': 'T008_schedule',
            },
        ),
        migrations.CreateModel(
            name='T007Contactbook',
            fields=[
                ('t007_pk01_contactbook_id', models.CharField(db_column='T007_PK01_contactbook-id', max_length=10, primary_key=True, serialize=False, verbose_name='連絡帳ID')),
                ('t007_fd13_updatedata', models.DateTimeField(db_column='T007_FD13_updatedata', verbose_name='保存or投稿日時')),
                ('t007_fd04_meal_contents', models.CharField(blank=True, db_column='T007_FD04_meal-contents', max_length=100, null=True, verbose_name='前夜食事内容')),
                ('t007_fd03_meal_time', models.TimeField(blank=True, db_column='T007_FD03_meal-time', null=True, verbose_name='前夜食事時間')),
                ('t007_fd13_breakfast_contents', models.CharField(blank=True, db_column='T007_FD13_bresakfast-contents', max_length=100, null=True, verbose_name='今朝食事内容')),
                ('t007_fd14_breakfast_time', models.TimeField(blank=True, db_column='T007_FD14_breakfast-time', null=True, verbose_name='今朝食事時間')),
                ('t007_fd06_wakeup_time', models.TimeField(blank=True, db_column='T007_FD06_wakeup-time', null=True, verbose_name='起床時間')),
                ('t007_fd07_mood', models.IntegerField(blank=True, db_column='T007_FD07_mood', null=True, verbose_name='機嫌')),
                ('t007_fd09_defecation_times', models.IntegerField(blank=True, db_column='T007_FD09_defecation-times', null=True, verbose_name='排便回数')),
                ('t007_fd08_defecation_status', models.IntegerField(blank=True, db_column='T007_FD08_defecation-status', null=True, verbose_name='排便状態')),
                ('t007_fd10_bathing', models.BooleanField(db_column='T007_FD10_bathing', default=True, verbose_name='入浴の有無')),
                ('t007_fd12_temperature', models.FloatField(blank=True, db_column='T007_FD12_temperature', null=True, verbose_name='検温')),
                ('t007_fd11_temperature_time', models.TimeField(blank=True, db_column='T007_FD11_temperature-time', null=True, verbose_name='検温時間')),
                ('t007_fd02_infomation', models.CharField(blank=True, db_column='T007_FD02_infomation', max_length=200, null=True, verbose_name='備考')),
                ('t007_fd25_pickup_person', models.CharField(choices=[('父', '父'), ('母', '母'), ('兄', '兄'), ('姉', '姉'), ('祖母', '祖母'), ('祖父', '祖父')], default='父', max_length=4, verbose_name='迎え人')),
                ('t007_fd26_pickup_time', models.TimeField(blank=True, null=True, verbose_name='迎え時間')),
                ('t007_fd15_lunch_contents', models.CharField(blank=True, db_column='T007_FD15_lunch-contents', max_length=100, null=True, verbose_name='昼食食事内容')),
                ('t007_fd16_lunch_time', models.TimeField(blank=True, db_column='T007_FD16_lunch-time', null=True, verbose_name='昼食食事時間')),
                ('t007_fd05_bed_time', models.TimeField(blank=True, null=True, verbose_name='就寝時間')),
                ('t007_fd17_wakeup_time', models.TimeField(blank=True, null=True, verbose_name='起床時間')),
                ('t007_fd18_mood', models.IntegerField(blank=True, null=True, verbose_name='機嫌')),
                ('t007_fd19_defecation_times', models.IntegerField(blank=True, null=True, verbose_name='排便回数')),
                ('t007_fd20_defecation_status', models.IntegerField(blank=True, null=True, verbose_name='排便状態')),
                ('t007_fd21_bathing', models.BooleanField(default=True, verbose_name='入浴の有無')),
                ('t007_fd22_temperature', models.FloatField(blank=True, null=True, verbose_name='検温')),
                ('t007_fd23_temperature_time', models.TimeField(blank=True, null=True, verbose_name='検温時間')),
                ('t007_fd24_infomation', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('t007_fd01_date', models.DateField(blank=True, db_column='T007_FD01_date', null=True, verbose_name='日付')),
                ('t007_fk01_children_id', models.ForeignKey(db_column='T007_FK01_children-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='main.t001children', verbose_name='園児ID')),
                ('t007_fk02_childminder_id', models.ForeignKey(db_column='T007_FK02_childminder-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.t003childminder', verbose_name='保育士ID')),
            ],
            options={
                'verbose_name_plural': '連絡帳テーブル',
                'db_table': 'T007_contactbook',
            },
        ),
        migrations.CreateModel(
            name='T006Message',
            fields=[
                ('t006_pk01_message_id', models.CharField(db_column='T006_PK01_message-id', max_length=100, primary_key=True, serialize=False, verbose_name='メッセージID')),
                ('t006_fd01_send_id', models.CharField(db_column='T006_FD01_send-id', max_length=10, verbose_name='送信者ID')),
                ('t006_fd02_contents', models.CharField(blank=True, db_column='T006_FD02_contents', max_length=200, null=True, verbose_name='内容')),
                ('t006_fd03_datetime', models.DateTimeField(db_column='T006_FD03_datetime', verbose_name='日時')),
                ('t006_fk01_room_id', models.ForeignKey(db_column='T006_FK01_room-id', default='1', max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='main.t011room', verbose_name='ルームID')),
            ],
            options={
                'verbose_name_plural': 'メッセージテーブル',
                'db_table': 'T006_message',
            },
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fk01_class_id',
            field=models.ForeignKey(db_column='T001_FK01_class-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='main.t004class', verbose_name='クラスID'),
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fk02_parents_id',
            field=models.ForeignKey(db_column='T001_FK02_parents-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.t002parents', verbose_name='保護者ID'),
        ),
        migrations.CreateModel(
            name='T009Position',
            fields=[
                ('t009_pk01_children_id', models.OneToOneField(db_column='T009_PK01_children-id', max_length=5, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.t001children', verbose_name='園児ID')),
                ('t009_pk02_datetime', models.DateTimeField(db_column='T009_PK02_datetime', verbose_name='日時')),
                ('t009_fd01_distance_a', models.FloatField(db_column='T009_FD01_distance-a', verbose_name='アンカーaからの遊具までの距離')),
                ('t009_fd02_distance_b', models.FloatField(db_column='T009_FD02_distance-b', verbose_name='アンカーbからの遊具までの距離')),
                ('t009_fd03_distance_c', models.FloatField(db_column='T009_FD03_distance-c', verbose_name='アンカーcからの遊具までの距離')),
                ('t009_fk01_playset_id', models.ForeignKey(db_column='T009_FK01_playset-id', default='1', max_length=10, on_delete=django.db.models.deletion.DO_NOTHING, to='main.t010playset', verbose_name='遊具ID')),
            ],
            options={
                'verbose_name_plural': '位置情報テーブル',
                'db_table': 'T009_position',
                'unique_together': {('t009_pk01_children_id', 't009_pk02_datetime')},
            },
        ),
    ]
