<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-16 06:36

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.9 on 2021-11-16 06:29

from django.db import migrations, models
>>>>>>> 213445dedaa73b8fb56b0ce1b27af2417e588453


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T001Children',
            fields=[
<<<<<<< HEAD
                ('t001_pk01_children_id', models.CharField(db_column='T001_PK01_children-id', max_length=5, primary_key=True, serialize=False, verbose_name='園児ID')),
                ('t001_fd01_name', models.CharField(db_column='T001_FD01_name', max_length=20, verbose_name='氏名')),
                ('t001_fd02_birthday', models.DateField(db_column='T001_FD02_birthday', verbose_name='誕生日')),
                ('t001_fd03_address', models.CharField(db_column='T001_FD03_address', max_length=50, verbose_name='住所')),
                ('t001_fd04_createdata', models.DateTimeField(db_column='T001_FD04_createdata', verbose_name='作成日時')),
                ('t001_fd05_updatedata', models.DateTimeField(blank=True, db_column='T001_FD05_updatedata', null=True, verbose_name='更新日時')),
                ('t001_fd06_sex', models.IntegerField(db_column='T001_FD06_sex', verbose_name='性別')),
            ],
            options={
                'verbose_name_plural': ('園児テーブル',),
=======
                ('t001_pk01_children_id', models.CharField(db_column='T001_PK01_children-id', max_length=5, primary_key=True, serialize=False)),
                ('t001_fd01_name', models.CharField(db_column='T001_FD01_name', max_length=20)),
                ('t001_fd02_birthday', models.DateField(db_column='T001_FD02_birthday')),
                ('t001_fd03_address', models.CharField(db_column='T001_FD03_address', max_length=50)),
                ('t001_fd04_createdata', models.DateTimeField(db_column='T001_FD04_createdata')),
                ('t001_fd05_updatedata', models.DateTimeField(blank=True, db_column='T001_FD05_updatedata', null=True)),
                ('t001_fd06_sex', models.IntegerField(db_column='T001_FD06_sex')),
            ],
            options={
>>>>>>> 213445dedaa73b8fb56b0ce1b27af2417e588453
                'db_table': 'T001_children',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T002Parents',
            fields=[
                ('t002_pk01_parents_id', models.CharField(db_column='T002_PK01_parents-id', max_length=5, primary_key=True, serialize=False)),
                ('t002_fd01_password', models.CharField(db_column='T002_FD01_password', max_length=100)),
                ('t002_fd02_name', models.CharField(blank=True, db_column='T002_FD02_name', max_length=50, null=True)),
                ('t002_fd03_birthday', models.DateField(db_column='T002_FD03_birthday')),
                ('t002_fd04_address', models.CharField(db_column='T002_FD04_address', max_length=100)),
                ('t002_fd05_mailadd', models.CharField(blank=True, db_column='T002_FD05_mailadd', max_length=255, null=True)),
                ('t002_fd06_notification', models.BooleanField(blank=True, db_column='T002_FD06_notification', null=True)),
                ('t002_fd07_telephonenum', models.CharField(db_column='T002_FD07_telephonenum', max_length=20)),
                ('t002_fd08_createdata', models.DateTimeField(db_column='T002_FD08_createdata')),
                ('t002_fd09_updatedata', models.DateTimeField(blank=True, db_column='T002_FD09_updatedata', null=True)),
                ('t002_fd10_sex', models.IntegerField(db_column='T002_FD10_sex')),
            ],
            options={
                'db_table': 'T002_parents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T003Childminder',
            fields=[
                ('t003_fd01_password', models.CharField(db_column='T003_FD01_password', max_length=100)),
                ('t003_fd02_name', models.CharField(blank=True, db_column='T003_FD02_name', max_length=50, null=True)),
                ('t003_fd03_birthday', models.DateField(db_column='T003_FD03_birthday')),
                ('t003_fd04_address', models.CharField(db_column='T003_FD04_address', max_length=100)),
                ('t003_fd05_mailadd', models.CharField(blank=True, db_column='T003_FD05_mailadd', max_length=255, null=True)),
                ('t003_fd06_administator', models.BooleanField(db_column='T003_FD06_administator')),
                ('t003_fd07_telephonenum', models.CharField(db_column='T003_FD07_telephonenum', max_length=20)),
                ('t003_fd08_createdata', models.DateTimeField(db_column='T003_FD08_createdata')),
                ('t003_fd09_updatedata', models.DateTimeField(blank=True, db_column='T003_FD09_updatedata', null=True)),
                ('t003_fd10_sex', models.IntegerField(db_column='T003_FD10_sex')),
                ('t003_fk01_childminder_id', models.CharField(db_column='T003_FK01_childminder-id', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'T003_childminder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T004Class',
            fields=[
                ('t004_pk01_class_id', models.CharField(db_column='T004_PK01_class-id', max_length=3, primary_key=True, serialize=False)),
                ('t004_fd01_class_name', models.CharField(db_column='T004_FD01_class-name', max_length=20)),
                ('t004_fd02_year', models.IntegerField(db_column='T004_FD02_year')),
            ],
            options={
                'db_table': 'T004_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='T005Kindergaten',
            fields=[
                ('t005_pk01_childen_id', models.CharField(db_column='T005_PK01_childen-id', max_length=5, primary_key=True, serialize=False)),
                ('t005_fd01_date', models.DateField(blank=True, db_column='T005_FD01_date', null=True)),
                ('t005_fd02_school_time', models.TimeField(blank=True, db_column='T005_FD02_school-time', null=True)),
                ('t005_fd03_exit_time', models.TimeField(blank=True, db_column='T005_FD03_exit-time', null=True)),
                ('t005_fd04_status', models.IntegerField(blank=True, db_column='T005_FD04_status', null=True)),
            ],
            options={
                'db_table': 'T005_kindergaten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
>>>>>>> 213445dedaa73b8fb56b0ce1b27af2417e588453
            name='T006Message',
            fields=[
                ('t006_pk01_message_id', models.CharField(db_column='T006_PK01_message-id', max_length=100, primary_key=True, serialize=False)),
                ('t006_fk01_room_id', models.CharField(db_column='T006_FK01_room-id', max_length=100)),
                ('t006_fd01_send_id', models.CharField(db_column='T006_FD01_send-id', max_length=10)),
                ('t006_fd02_contents', models.CharField(blank=True, db_column='T006_FD02_contents', max_length=200, null=True)),
                ('t006_fd03_datetime', models.DateTimeField(db_column='T006_FD03_datetime')),
                ('t006_fd04_emergency', models.BooleanField(db_column='T006_FD04_emergency')),
            ],
            options={
                'db_table': 'T006_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T007Contactbook',
            fields=[
                ('t007_pk01_contactbook_id', models.CharField(db_column='T007_PK01_contactbook-id', max_length=10, primary_key=True, serialize=False)),
                ('t007_fd13_updatedata', models.DateTimeField(db_column='T007_FD13_updatedata')),
                ('t007_fd12_temperature', models.FloatField(blank=True, db_column='T007_FD12_temperature', null=True)),
                ('t007_fd11_temperature_time', models.TimeField(blank=True, db_column='T007_FD11_temperature-time', null=True)),
                ('t007_fd10_bathing', models.BooleanField(blank=True, db_column='T007_FD10_bathing', null=True)),
                ('t007_fd09_defecation_times', models.IntegerField(blank=True, db_column='T007_FD09_defecation-times', null=True)),
                ('t007_fd08_defecation_status', models.CharField(blank=True, db_column='T007_FD08_defecation-status', max_length=10, null=True)),
                ('t007_fd07_mood', models.CharField(blank=True, db_column='T007_FD07_mood', max_length=10, null=True)),
                ('t007_fd06_wakeup_time', models.TimeField(blank=True, db_column='T007_FD06_wakeup-time', null=True)),
                ('t007_fd05_bed_time', models.TimeField(blank=True, db_column='T007_FD05_bed-time', null=True)),
                ('t007_fd04_meal_contents', models.CharField(blank=True, db_column='T007_FD04_meal-contents', max_length=100, null=True)),
                ('t007_fd03_meal_time', models.TimeField(blank=True, db_column='T007_FD03_meal-time', null=True)),
                ('t007_fd02_infomation', models.CharField(blank=True, db_column='T007_FD02_infomation', max_length=200, null=True)),
                ('t007_fd01_date', models.DateField(blank=True, db_column='T007_FD01_date', null=True)),
            ],
            options={
                'db_table': 'T007_contactbook',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T008Schedule',
            fields=[
                ('t008_pk01_schedule_id', models.CharField(db_column='T008_PK01_schedule-id', max_length=10, primary_key=True, serialize=False)),
                ('t008_fd01_event', models.CharField(db_column='T008_FD01_event', max_length=100)),
                ('t008_fd02_remarks', models.CharField(blank=True, db_column='T008_FD02_remarks', max_length=200, null=True)),
                ('t008_fd03_date', models.DateField(db_column='T008_FD03_date')),
                ('t008_fd04_updatedata', models.DateTimeField(db_column='T008_FD04_updatedata')),
                ('t008_fd05_createdata', models.DateTimeField(blank=True, db_column='T008_FD05_createdata', null=True)),
                ('t008_fd06_time', models.TimeField(blank=True, db_column='T008_FD06_time', null=True)),
            ],
            options={
                'db_table': 'T008_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T009Position',
            fields=[
                ('t009_pk01_children_id', models.CharField(db_column='T009_PK01_children-id', max_length=5, primary_key=True, serialize=False)),
                ('t009_pk02_datetime', models.DateTimeField(db_column='T009_PK02_datetime')),
                ('t009_fk01_playset_id', models.CharField(db_column='T009_FK01_playset-id', max_length=10)),
                ('t009_fd01_distance_a', models.FloatField(db_column='T009_FD01_distance-a')),
                ('t009_fd02_distance_b', models.FloatField(db_column='T009_FD02_distance-b')),
                ('t009_fd03_distance_c', models.FloatField(db_column='T009_FD03_distance-c')),
            ],
            options={
                'db_table': 'T009_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T010Playset',
            fields=[
                ('t010_pk01_playset_id', models.CharField(db_column='T010_PK01_playset-id', max_length=10, primary_key=True, serialize=False)),
                ('t010_fd01_playset_name', models.CharField(db_column='T010_FD01_playset-name', max_length=30)),
                ('t010_fd02_distance_a', models.FloatField(db_column='T010_FD02_distance-a')),
                ('t010_fd03_distance_b', models.FloatField(blank=True, db_column='T010_FD03_distance-b', null=True)),
                ('t010_fd04_distance_c', models.FloatField(db_column='T010_FD04_distance-c')),
            ],
            options={
                'db_table': 'T010_playset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T011Room',
            fields=[
                ('t011_pk01_room_id', models.CharField(db_column='T011_PK01_room-id', max_length=100, primary_key=True, serialize=False)),
                ('t011_fk02_chilminder_id', models.CharField(db_column='T011_FK02_chilminder-id', max_length=5)),
            ],
            options={
                'db_table': 'T011_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T012Contactbooktem',
            fields=[
                ('t012_pk01_contactbook_id', models.CharField(db_column='T012_PK01_contactbook-id', max_length=10, primary_key=True, serialize=False)),
                ('t012_fd01_date', models.DateField(blank=True, db_column='T012_FD01_date', null=True)),
                ('t012_fd02_information', models.CharField(blank=True, db_column='T012_FD02_information', max_length=200, null=True)),
                ('t012_fd03_mealtime', models.TextField(blank=True, db_column='T012_FD03_mealtime', null=True)),
                ('t012_fd04_meal_contents', models.CharField(blank=True, db_column='T012_FD04_meal-contents', max_length=100, null=True)),
                ('t012_fd05_bed_time', models.TimeField(blank=True, db_column='T012_FD05_bed-time', null=True)),
                ('t012_fd06_wakeup_time', models.TimeField(blank=True, db_column='T012_FD06_wakeup-time', null=True)),
                ('t012_fd07_updatedata', models.DateTimeField(db_column='T012_FD07_updatedata')),
            ],
            options={
                'db_table': 'T012_contactbooktem',
                'managed': False,
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='T005Kindergaten',
            fields=[
                ('t005_pk01_childen_id', models.ForeignKey(db_column='T005_PK01_childen-id', max_length=5, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.t001children')),
                ('t005_fd01_date', models.DateField(blank=True, db_column='T005_FD01_date', null=True)),
                ('t005_fd02_school_time', models.TimeField(blank=True, db_column='T005_FD02_school-time', null=True)),
                ('t005_fd03_exit_time', models.TimeField(blank=True, db_column='T005_FD03_exit-time', null=True)),
                ('t005_fd04_status', models.IntegerField(blank=True, db_column='T005_FD04_status', null=True)),
            ],
            options={
                'db_table': 'T005_kindergaten',
                'managed': False,
            },
        ),
=======
>>>>>>> 213445dedaa73b8fb56b0ce1b27af2417e588453
    ]
