# Generated by Django 3.2.9 on 2021-11-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t001children',
            options={'managed': False, 'verbose_name_plural': '園児テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t002parents',
            options={'managed': False, 'verbose_name_plural': '保護者テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t003childminder',
            options={'managed': False, 'verbose_name_plural': '保育士テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t004class',
            options={'managed': False, 'verbose_name_plural': 'クラステーブル'},
        ),
        migrations.AlterModelOptions(
            name='t005kindergaten',
            options={'managed': False, 'verbose_name_plural': '登園状態テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t006message',
            options={'managed': False, 'verbose_name_plural': 'メッセージテーブル'},
        ),
        migrations.AlterModelOptions(
            name='t007contactbook',
            options={'managed': False, 'verbose_name_plural': '連絡帳テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t008schedule',
            options={'managed': False, 'verbose_name_plural': 'スケジュールテーブル'},
        ),
        migrations.AlterModelOptions(
            name='t009position',
            options={'managed': False, 'verbose_name_plural': '位置情報テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t010playset',
            options={'managed': False, 'verbose_name_plural': '遊具テーブル'},
        ),
        migrations.AlterModelOptions(
            name='t011room',
            options={'managed': False, 'verbose_name_plural': 'ルームテーブル'},
        ),
        migrations.AlterModelOptions(
            name='t012contactbooktem',
            options={'managed': False, 'verbose_name_plural': '連絡帳テンプレートテーブル'},
        ),
    ]
