# Generated by Django 3.2.9 on 2021-11-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t001children',
            name='t001_fd01_name',
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fd01_last_name',
            field=models.CharField(db_column='T001_FD01_name', default='1', max_length=20, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fd07_first_name',
            field=models.CharField(default='1', max_length=20, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fd08_last_name_kana',
            field=models.CharField(default='1', max_length=20, verbose_name='姓（かな）'),
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fd09_first_name_kana',
            field=models.CharField(default='1', max_length=20, verbose_name='名（かな）'),
        ),
        migrations.AddField(
            model_name='t001children',
            name='t001_fd10_postal_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号（ハイフンなし）'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd06_sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], db_column='T001_FD06_sex', default='1', max_length=4, verbose_name='性別'),
        ),
    ]
