# Generated by Django 3.2.9 on 2021-12-01 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd04_createdata',
            field=models.DateTimeField(blank=True, db_column='T001_FD04_createdata', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='t006message',
            name='t006_fd03_datetime',
            field=models.DateTimeField(auto_now=True, db_column='T006_FD03_datetime', null=True, verbose_name='日時'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd01_date',
            field=models.DateField(blank=True, db_column='T007_FD01_date', default=datetime.date.today, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='t008schedule',
            name='t008_fd04_updatedata',
            field=models.DateTimeField(auto_now_add=True, db_column='T008_FD04_updatedata', verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='t008schedule',
            name='t008_fd05_createdata',
            field=models.DateTimeField(auto_now=True, db_column='T008_FD05_createdata', null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='t012contactbooktem',
            name='t012_fd07_updatedata',
            field=models.DateTimeField(auto_now=True, db_column='T012_FD07_updatedata', verbose_name='更新日時'),
        ),
    ]
