# Generated by Django 3.2.9 on 2021-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd25_pickup_person',
            field=models.CharField(choices=[('父', '父'), ('母', '母'), ('兄', '兄'), ('姉', '姉'), ('祖母', '祖母'), ('祖父', '祖父'), ('バス', 'バス')], default='父', max_length=4, verbose_name='迎え人'),
        ),
    ]
