# Generated by Django 3.2.9 on 2021-11-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t009position',
            name='t009_fd02_distance_b',
            field=models.FloatField(blank=True, db_column='T009_FD02_distance-b', null=True, verbose_name='アンカーbからの遊具までの距離'),
        ),
    ]
