# Generated by Django 3.2.9 on 2021-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211201_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd04_createdata',
            field=models.DateTimeField(auto_now_add=True, db_column='T001_FD04_createdata', null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd05_updatedata',
            field=models.DateTimeField(auto_now=True, db_column='T001_FD05_updatedata', null=True, verbose_name='更新日時'),
        ),
    ]
