# Generated by Django 3.2.9 on 2021-12-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_t007contactbook_t007_fd25_pickup_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fk01_class_id',
            field=models.ForeignKey(db_column='T001_FK01_class-id', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='main.t004class', verbose_name='クラス名'),
        ),
    ]
