# Generated by Django 3.2.9 on 2021-11-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211129_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd13_breakfast_contents',
            field=models.CharField(blank=True, db_column='T007_FD13_bresakfast-contents', max_length=100, null=True, verbose_name='今朝食事内容'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd14_breakfast_time',
            field=models.TimeField(blank=True, db_column='T007_FD14_breakfast-time', null=True, verbose_name='今朝食事時間'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd15_lunch_contents',
            field=models.CharField(blank=True, db_column='T007_FD15_lunch-contents', max_length=100, null=True, verbose_name='昼食食事内容'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd16_lunch_time',
            field=models.TimeField(blank=True, db_column='T007_FD16_lunch-time', null=True, verbose_name='昼食食事時間'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd17_wakeup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='起床時間'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd18_mood',
            field=models.IntegerField(blank=True, null=True, verbose_name='機嫌'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd19_defecation_times',
            field=models.IntegerField(blank=True, null=True, verbose_name='排便回数'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd20_defecation_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='排便状態'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd21_bathing',
            field=models.BooleanField(default=True, verbose_name='入浴の有無'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd22_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='検温'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd23_temperature_time',
            field=models.TimeField(blank=True, null=True, verbose_name='検温時間'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd24_infomation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd25_pickup_person',
            field=models.CharField(choices=[('父', '父'), ('母', '母'), ('兄', '兄'), ('姉', '姉'), ('祖母', '祖母'), ('祖父', '祖父')], default='父', max_length=4, verbose_name='迎え人'),
        ),
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd26_pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='迎え時間'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd06_sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性')], db_column='T001_FD06_sex', default='男性', max_length=4, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='t005kindergaten',
            name='t005_fd04_status',
            field=models.CharField(choices=[('登園', '登園'), ('降園', '降園')], db_column='T005_FD04_status', default='登園', max_length=4, verbose_name='登園状態'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd03_meal_time',
            field=models.TimeField(blank=True, db_column='T007_FD03_meal-time', null=True, verbose_name='前夜食事時間'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd04_meal_contents',
            field=models.CharField(blank=True, db_column='T007_FD04_meal-contents', max_length=100, null=True, verbose_name='前夜食事内容'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd05_bed_time',
            field=models.TimeField(blank=True, null=True, verbose_name='就寝時間'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd07_mood',
            field=models.IntegerField(blank=True, db_column='T007_FD07_mood', null=True, verbose_name='機嫌'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd08_defecation_status',
            field=models.IntegerField(blank=True, db_column='T007_FD08_defecation-status', null=True, verbose_name='排便状態'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd10_bathing',
            field=models.BooleanField(db_column='T007_FD10_bathing', default=True, verbose_name='入浴の有無'),
        ),
    ]
