# Generated by Django 3.2.9 on 2021-11-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211118_0946'),
        ('main', '0002_auto_20211119_0954'),
    ]

    operations = [
    ]
