# Generated by Django 3.2.9 on 2021-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_t001children_t001_fk01_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t005kindergaten',
            name='t005_fd04_status',
            field=models.CharField(choices=[('登園', '登園'), ('降園', '降園'), ('遅刻', '遅刻'), ('早退', '早退')], db_column='T005_FD04_status', default='登園', max_length=4, verbose_name='登園状態'),
        ),
    ]
