# Generated by Django 3.2.9 on 2021-11-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211130_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd01_last_name',
            field=models.CharField(default='1', max_length=20, verbose_name='姓'),
        ),
    ]
