# Generated by Django 3.2.9 on 2021-12-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_t005kindergaten_t005_fd04_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd27_bed_time',
            field=models.TimeField(blank=True, null=True, verbose_name='就寝時間'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd05_bed_time',
            field=models.TimeField(blank=True, db_column='T007_FD05_bed-time', null=True, verbose_name='就寝時間'),
        ),
    ]
