# Generated by Django 3.2.9 on 2021-11-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_t009position_t009_fd02_distance_b'),
        ('main', '0004_alter_t001children_t001_fd01_last_name'),
    ]

    operations = [
    ]
