# Generated by Django 3.2.9 on 2021-11-30 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20211130_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd01_last_name',
            field=models.CharField(max_length=20, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd07_first_name',
            field=models.CharField(max_length=20, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd08_last_name_kana',
            field=models.CharField(max_length=20, verbose_name='姓（かな）'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fd09_first_name_kana',
            field=models.CharField(max_length=20, verbose_name='名（かな）'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_pk01_children_id',
            field=models.CharField(db_column='T001_PK01_children-id', max_length=5, primary_key=True, serialize=False, verbose_name='園児ID'),
        ),
        migrations.AlterField(
            model_name='t005kindergaten',
            name='t005_fd01_date',
            field=models.DateField(db_column='T005_FD01_date', default=datetime.date.today, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd13_updatedata',
            field=models.DateTimeField(db_column='T007_FD13_updatedata', verbose_name='保存or投稿日時'),
        ),
        migrations.AlterField(
            model_name='t009position',
            name='t009_fd02_distance_b',
            field=models.FloatField(db_column='T009_FD02_distance-b', verbose_name='アンカーbからの遊具までの距離'),
        ),
        migrations.AlterField(
            model_name='t010playset',
            name='t010_fd03_distance_b',
            field=models.FloatField(db_column='T010_FD03_distance-b', verbose_name='アンカーbからの遊具までの距離'),
        ),
    ]
