# Generated by Django 3.2.9 on 2021-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211222_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='T013Blog',
            fields=[
                ('t013_pk01_blog_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ブログID')),
                ('t013_fd01_title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('t013_fd02_content', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('t013_fd03_photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真１')),
                ('t013_fd04_photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真２')),
                ('t013_fd05_photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真３')),
                ('t013_fd06_updatedata', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('t013_fd07_createdata', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'ブログテーブル',
                'db_table': 'T013_blog',
            },
        ),
    ]
