# Generated by Django 3.2.9 on 2021-12-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_t013blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t013blog',
            old_name='t013_fd06_updatedata',
            new_name='t013_fd06_createdata',
        ),
        migrations.RenameField(
            model_name='t013blog',
            old_name='t013_fd07_createdata',
            new_name='t013_fd07_updatedata',
        ),
    ]
