# Generated by Django 3.2.9 on 2022-01-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211227_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t013blog',
            name='t013_pk01_blog_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ブログID'),
        ),
    ]
