# Generated by Django 3.2.9 on 2022-01-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_t013blog_t013_pk01_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t001children',
            name='t001_fd11_kindergaten',
            field=models.BooleanField(default='True', verbose_name='登園状態'),
        ),
    ]
