# Generated by Django 3.2.9 on 2022-01-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_t001children_t001_fd11_kindergaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_fd28_person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='記入者'),
        ),
    ]
