# Generated by Django 3.2.9 on 2022-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_t007contactbook_t007_fd28_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='t012contactbooktem',
            name='t023_fd08_person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='記入者'),
        ),
    ]
