# Generated by Django 3.2.9 on 2022-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_t012contactbooktem_t023_fd08_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t012contactbooktem',
            name='t012_fd02_information',
            field=models.TextField(blank=True, db_column='T012_FD02_information', max_length=200, null=True, verbose_name='備考'),
        ),
    ]
