# Generated by Django 3.2.9 on 2022-01-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_t012contactbooktem_t023_fd08_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t007contactbook',
            name='t007_fd28_person',
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd07_mood',
            field=models.IntegerField(blank=True, choices=[('good', '良'), ('usually', '普'), ('bad', '悪')], db_column='T007_FD07_mood', null=True, verbose_name='機嫌'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd08_defecation_status',
            field=models.IntegerField(blank=True, choices=[('water', '水'), ('soft', '軟'), ('usually', '普'), ('hard', '硬')], db_column='T007_FD08_defecation-status', null=True, verbose_name='排便状態'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd09_defecation_times',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], db_column='T007_FD09_defecation-times', null=True, verbose_name='排便回数'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd10_bathing',
            field=models.BooleanField(choices=[('y', '有'), ('n', '無')], db_column='T007_FD10_bathing', default=True, verbose_name='入浴の有無'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd12_temperature',
            field=models.FloatField(blank=True, choices=[('34.0', '34.0'), ('34.1', '34.1'), ('34.2', '34.2'), ('34.3', '34.3'), ('34.4', '34.4'), ('34.5', '34.5'), ('34.6', '34.6'), ('34.7', '34.7'), ('34.8', '34.8'), ('34.9', '34.9'), ('35.0', '35.0'), ('35.1', '35.1'), ('35.2', '35.2'), ('35.3', '35.3'), ('35.4', '35.4'), ('35.5', '35.5'), ('35.6', '35.6'), ('35.7', '35.7'), ('35.8', '35.8'), ('35.9', '35.9'), ('36.0', '36.0'), ('36.1', '36.1'), ('36.2', '36.2'), ('36.3', '36.3'), ('36.4', '36.4'), ('36.5', '36.5'), ('36.6', '36.6'), ('36.7', '36.7'), ('36.8', '36.8'), ('36.9', '36.9'), ('37.0', '37.0'), ('37.1', '37.1'), ('37.2', '37.2'), ('37.3', '37.3'), ('37.4', '37.4'), ('37.5', '37.5'), ('37.6', '37.6'), ('37.7', '37.7'), ('37.8', '37.8'), ('37.9', '37.9'), ('38.0', '38.0'), ('38.1', '38.1'), ('38.2', '38.2'), ('38.3', '38.3'), ('38.4', '38.4'), ('38.5', '38.5'), ('38.6', '38.6'), ('38.7', '38.7'), ('38.8', '38.8'), ('38.9', '38.9'), ('39.0', '39.0'), ('39.1', '39.1'), ('39.2', '39.2'), ('39.3', '39.3'), ('39.4', '39.4'), ('39.5', '39.5'), ('39.6', '39.6'), ('39.7', '39.7'), ('39.8', '39.8'), ('39.9', '39.9'), ('40', '40')], db_column='T007_FD12_temperature', null=True, verbose_name='検温'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd18_mood',
            field=models.IntegerField(blank=True, choices=[('good', '良'), ('usually', '普'), ('bad', '悪')], null=True, verbose_name='機嫌'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd19_defecation_times',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='排便回数'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd20_defecation_status',
            field=models.IntegerField(blank=True, choices=[('water', '水'), ('soft', '軟'), ('usually', '普'), ('hard', '硬')], null=True, verbose_name='排便状態'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd21_bathing',
            field=models.BooleanField(choices=[('y', '有'), ('n', '無')], default=True, verbose_name='入浴の有無'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd22_temperature',
            field=models.FloatField(blank=True, choices=[('34.0', '34.0'), ('34.1', '34.1'), ('34.2', '34.2'), ('34.3', '34.3'), ('34.4', '34.4'), ('34.5', '34.5'), ('34.6', '34.6'), ('34.7', '34.7'), ('34.8', '34.8'), ('34.9', '34.9'), ('35.0', '35.0'), ('35.1', '35.1'), ('35.2', '35.2'), ('35.3', '35.3'), ('35.4', '35.4'), ('35.5', '35.5'), ('35.6', '35.6'), ('35.7', '35.7'), ('35.8', '35.8'), ('35.9', '35.9'), ('36.0', '36.0'), ('36.1', '36.1'), ('36.2', '36.2'), ('36.3', '36.3'), ('36.4', '36.4'), ('36.5', '36.5'), ('36.6', '36.6'), ('36.7', '36.7'), ('36.8', '36.8'), ('36.9', '36.9'), ('37.0', '37.0'), ('37.1', '37.1'), ('37.2', '37.2'), ('37.3', '37.3'), ('37.4', '37.4'), ('37.5', '37.5'), ('37.6', '37.6'), ('37.7', '37.7'), ('37.8', '37.8'), ('37.9', '37.9'), ('38.0', '38.0'), ('38.1', '38.1'), ('38.2', '38.2'), ('38.3', '38.3'), ('38.4', '38.4'), ('38.5', '38.5'), ('38.6', '38.6'), ('38.7', '38.7'), ('38.8', '38.8'), ('38.9', '38.9'), ('39.0', '39.0'), ('39.1', '39.1'), ('39.2', '39.2'), ('39.3', '39.3'), ('39.4', '39.4'), ('39.5', '39.5'), ('39.6', '39.6'), ('39.7', '39.7'), ('39.8', '39.8'), ('39.9', '39.9'), ('40', '40')], null=True, verbose_name='検温'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd25_pickup_person',
            field=models.CharField(choices=[('父', '父'), ('母', '母'), ('兄', '兄'), ('姉', '姉'), ('祖父', '祖父'), ('祖母', '祖母'), ('バス', 'バス')], default='父', max_length=4, verbose_name='迎え人'),
        ),
        migrations.AlterField(
            model_name='t012contactbooktem',
            name='t012_fd02_information',
            field=models.TextField(blank=True, db_column='T012_FD02_information', max_length=200, null=True, verbose_name='備考'),
        ),
    ]
