# Generated by Django 3.2.9 on 2022-01-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_t012contactbooktem_t012_fd02_information'),
        ('main', '0012_auto_20220124_1504'),
    ]

    operations = [
    ]
