# Generated by Django 3.2.9 on 2022-01-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20220125_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='t007contactbook',
            name='t007_f28_person',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='記入者'),
        ),
    ]
