# Generated by Django 3.2.9 on 2022-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_t007contactbook_t007_f28_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t012contactbooktem',
            name='t012_pk01_contactbook_id',
            field=models.AutoField(db_column='T012_PK01_contactbook-id', max_length=10, primary_key=True, serialize=False, verbose_name='連絡帳テンプレートID'),
        ),
    ]
