# Generated by Django 3.2.9 on 2022-01-26 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220125_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd13_updatedata',
            field=models.DateTimeField(db_column='T007_FD13_updatedata', default=datetime.datetime.now, verbose_name='保存or投稿日時'),
        ),
    ]
