# Generated by Django 3.2.9 on 2022-01-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_t007contactbook_t007_fd13_updatedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t007contactbook',
            old_name='t007_f28_person',
            new_name='t007_fd28_person',
        ),
        migrations.RemoveField(
            model_name='t012contactbooktem',
            name='t023_fd08_person',
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd07_mood',
            field=models.IntegerField(blank=True, choices=[(1, '良'), (2, '普'), (3, '悪')], db_column='T007_FD07_mood', null=True, verbose_name='機嫌'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd08_defecation_status',
            field=models.IntegerField(blank=True, choices=[(1, '水'), (2, '軟'), (3, '普'), (4, '硬')], db_column='T007_FD08_defecation-status', null=True, verbose_name='排便状態'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd18_mood',
            field=models.IntegerField(blank=True, choices=[(1, '良'), (2, '普'), (3, '悪')], null=True, verbose_name='機嫌'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_fd20_defecation_status',
            field=models.IntegerField(blank=True, choices=[(1, '水'), (2, '軟'), (3, '普'), (4, '硬')], null=True, verbose_name='排便状態'),
        ),
    ]
