# Generated by Django 3.2.9 on 2022-01-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220126_1214'),
        ('main', '0021_alter_t012contactbooktem_t012_pk01_contactbook_id'),
    ]

    operations = [
    ]
