# Generated by Django 3.2.9 on 2022-02-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220204_1638'),
        ('main', '0022_merge_20220127_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t001children',
            name='t001_fk01_class_id',
            field=models.ForeignKey(blank=True, db_column='T001_FK01_class-id', default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.t004class', verbose_name='クラス名'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_fk02_parents_id',
            field=models.ForeignKey(blank=True, db_column='T001_FK02_parents-id', default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.t002parents', verbose_name='保護者ID'),
        ),
        migrations.AlterField(
            model_name='t001children',
            name='t001_pk01_children_id',
            field=models.CharField(db_column='T001_PK01_children-id', max_length=50, primary_key=True, serialize=False, verbose_name='園児ID'),
        ),
        migrations.AlterField(
            model_name='t007contactbook',
            name='t007_pk01_contactbook_id',
            field=models.CharField(db_column='T007_PK01_contactbook-id', max_length=60, primary_key=True, serialize=False, verbose_name='連絡帳ID'),
        ),
        migrations.AlterField(
            model_name='t012contactbooktem',
            name='t012_pk01_contactbook_id',
            field=models.AutoField(db_column='T012_PK01_contactbook-id', primary_key=True, serialize=False, verbose_name='連絡帳テンプレートID'),
        ),
    ]
